### ISSUE TITLE
"bypass"

### ISSUE THREAD

**Issue by UnEnanoMas** [Se7en-dev/StopAFK#4]
![image](https://user-images.githubusercontent.com/63286108/94194661-4a282480-feb2-11ea-82fe-6d03581821ca.png)

**Comment by UnEnanoMas** [comment]
Anti AFK font keeps gamers still afk xd

**Comment by Se7en-dev** [comment]
That's logic lmao
The plugin checks if the position of players has changed since the last check, with these kind of contraptions the players won't be kicked...

I can't do anything about that
Just forbid them on your server lol

**Comment by UnEnanoMas** [comment]
There has to be something to check the player's movement, that is, if the camera moves, the body moves, isn't there something to check if the body doesn't move?
